const words = [
      { ja: "変数", fr: "variable", en: "variable",desc: "データを一時的に記憶しておく領域に名前を付けたもの。" },
      { ja: "定数", fr: "constante", en: "constant",desc: "変更できない値。" },
      { ja: "バッククオート", fr: "accent grave", en: "grave accent",desc: "JavaScriptでテンプレートリテラルに使う。改行をそのまま改行として扱ったり、変数や式を${変数名・式}のように埋め込める。backtickとも。" },
      { ja: "比較演算子", fr: "opérateur de comparaison", en: "comparison operator",desc: "関係演算子ともいう。これを含む式は関係式または条件と呼ばれる。" },
      { ja: "構文", fr: "syntaxe", en: "syntax",desc: "プログラムの文法や規則、構文のこと。シンタックスエラーはコンパイル時の構文エラー。" },
      { ja: "関数", fr: "fonction", en: "function",desc: "ある決まった処理を行うプログラムの集合。" },
      { ja: "引数", fr: "argument", en: "argument",desc: "関数やメソッドに渡される値や変数。" },
      { ja: "値", fr: "valeur", en: "value",desc: "何らかのデータ型を持つ単一のデータ。" },
      { ja: "戻り値", fr: "retour", en: "return",desc: "関数やメソッド、サブルーチンなどが処理を終了する際に呼び出し元に返す値。" },
      { ja: "型", fr: "type", en: "type",desc: "データの扱われ方をコンパイラやインタープリタに知らせるための分類。" },
      { ja: "配列", fr: "tableau", en: "array",desc: "同一の型のデータをメモリ上に一列に並べたもの。配列内の各データを要素という。" },
      { ja: "オブジェクト", fr: "objet", en: "object",desc: "データとそのデータを操作する手段を一つにまとめたもの。クラスとして定義し、それをもとにオブジェクト(インスタンス)を作ることもあるが、言語によっては全てのオブジェクトがインスタンスというわけではない。" },
      { ja: "メソッド", fr: "méthode", en: "method",desc: "クラス内の関数。" },
      { ja: "クラス", fr: "classe", en: "class",desc: "オブジェクトを生成するための設計図。" },
      { ja: "インスタンス", fr: "instance", en: "instance",desc: "クラスから生成されたオブジェクト。インスタンスはオブジェクトでもあるため、オブジェクトとも呼ばれる。" },
      { ja: "if文", fr: "instruction conditionnelle", en: "conditional",desc: "条件式。Javaは{}が必須。JavaScriptは一行なら{}省略可。Pythonは：とインデントでブロックを表現し、else ifはelif。" },
      { ja: "switch文", fr: "instruction switch", en: "switch statement",desc: "値に応じた条件分岐。C、C++、Java、JavaScript、Goはbreakを書かないとフォールスルー。" },
      { ja: "for文", fr: "boucle for", en: "for statement",desc: "条件が真の間だけ実行を繰り返す。whileループとは異なり初期化が必要。" },
      { ja: "while文", fr: "boucle while", en: "while statement",desc: "条件式が偽の場合一度もループは実行されない。GoやPythonにはないdo while分ではループは一度は実行される。" },
      { ja: "ブレイク", fr: "interrompre", en: "break",desc: "ループやswitch文の処理を途中で終了させる。" },
      { ja: "コンティニュー", fr: "continue", en: "continuer",desc: "処理をスキップして、次のループへ進む。" },
      { ja: "余り", fr: "reste", en: "remainder",desc: "割り算の余り" },
      { ja: "ライブラリ", fr: "bibliothèque", en: "library",desc: "よく使う処理や機能をまとめた再利用可能なプログラムの部品集のこと。日付処理、文字列操作、HTTP通信、グラフ描画などの決まった目的や機能に特化している。JavaScriptではjQuery, Lodash, Axiosなど。" },
      { ja: "依存関係", fr: "dépendance", en: "dependency",desc: "あるソフトウェアやプログラムが動作するために他のソフトウェアやライブラリに依存している関係のこと。大規模プロジェクトでは依存関係が複雑になりやすいのでパッケージ管理ツールで管理する。" },
      { ja: "実行時", fr: "exécution", en: "runtime",desc: "プログラムが実行されている間のこと、またはその実行環境のこと" },
      { ja: "スコープ", fr: "portée", en: "scope",desc: "変数や関数が有効・参照できる範囲のこと。ローカルスコープやグローバルスコープなどがある。" },
      { ja: "プロパティ", fr: "propriété", en: "property",desc: "オブジェクト指向プログラミングでオブジェクトが持つデータ（値）を外部からアクセス・変更するための仕組みのこと。" },
      { ja: "フォールスルー", fr: "fall through", en: "fall through",desc: "switch文またはcase文で、次のケースにそのまま流れ込む動作 のこと。tomber à travers または passer au travers。" },
      { ja: "半導体", fr: "semi-conducteur", en: "semiconductor",desc: "導体と絶縁体の中間にある物質のこと。温度や電圧、光などの条件によって電気を通したり通さなかったりできる。主な材料は シリコン。"},
      { ja: "基盤", fr: "carte de circuit", en: "circuit board",desc: "電子部品（抵抗・コンデンサ・ICなど）を取り付けて、電気信号をつなぐための板状の部品 のこと。" },
      { ja: "メモリ", fr: "mémoire vive", en: "memory",desc: "RAM (random access memory)のこと。作業中のデータを一時的に保存する場所。" },
      { ja: "ストレージ", fr: "stockage", en: "storage",desc: "データを長期的に保存する場所。" },
      { ja: "HDD", fr: "disque dur", en: "HDD",desc: "ハードディスクドライブ、一般的にはハードディスクと呼ばれる。中には 円盤（ディスク）が入っており、その表面に磁気でデータを書き込む。モーターで円盤が回転し、読み書き用のヘッドが動いてデータを読み取る。SSDより遅く衝撃に弱いが、容量は大きい。" },
      { ja: "SSD", fr: "SSD", en: "",desc: "solid state drive、フラッシュメモリ。データを電子的に保存するストレージ。HDDに比べ速度が速く衝撃に強いが価格が高い。" },
      { ja: "揮発性", fr: "volatile", en: "volatile",desc: "電源を切るとデータが消える性質のこと。" },
      { ja: "RAM", fr: "RAM", en: "RAM",desc: "ランダムアクセスメモリの略で、日本語では主記憶装置やメモリとも呼ばれる。RAMが多いほど同時に多くのアプリを開け、動作がスムーズになり、大きなデータも快適に扱える。" },
      { ja: "ROM", fr: "ROM", en: "ROM",desc: "リードオンリーメモリの略で、起動プログラムなどの消さないデータを保存するメモリ。mémoire morteとも呼ばれる。" },
      { ja: "GPU", fr: "GPU", en: "GPU",desc: "graphics processing unitの略で、主に画像や映像の処理を高速で行うためのコンピュータチップ。" },
      { ja: "クレデンシャル", fr: "identifiant", en: "credential",desc: "身元を証明するための情報や認証に使う証拠のこと。ユーザー名、パスワード、暗証番号、指紋・顔認証、APIキー、アクセストークンなど。" },
      { ja: "スクレイピング", fr: "extraction", en: "Scraping",desc: "webサイトから自動的に情報を取得する技術や手法のこと。サイトの規約でスクレイピング禁止となっていることがある。" },
      { ja: "圧縮", fr: "compression", en: "compression",desc: "データの中にある重複や無駄な部分を減らしてサイズを小さくする技術のこと。" },
      { ja: "展開", fr: "décompression", en: "decompression",desc: "圧縮によって小さくされたデータを元の形に戻す処理のこと。" },
      { ja: "三項演算子", fr: "opérateur ternaire", en: "ternary operator",desc: "(条件式 ? 真の場合の値 : 偽の場合の値)という形で、if文を1行で書ける演算子のこと。"},
      { ja: "修飾子", fr: "modificateur", en: "modifier",desc: "変数やメソッドに性質を与えるキーワード（例：public, private, static, final）" },
      { ja: "ジェネリクス", fr: "génériques", en: "generics",desc: "クラスや関数、メソッドなどに対して扱うデータ型を抽象化して定義できる仕組み。" },
      { ja: "型推論", fr: "inférence de type", en: "type inference",desc: "変数や式の型を自動で推測してくれる仕組みのこと" },
      { ja: "型指定", fr: "spécification de type", en: "type annotation",desc: "変数や関数に対して、扱うデータの型を明示的に指定すること。" },
      { ja: "コールバック関数", fr: "fonction de rappel", en: "callback function",desc: "他の関数に後で呼び出してほしい処理を渡すための関数 のこと。タイマーやイベント処理、非同期処理などに使う。" },
      { ja: "CDN", fr: "CDN", en: "CDN",desc: "content delivery network。ユーザーに最も近いサーバーからコンテンツを配信することで高速化する分散型ネットワークのこと。元のコンテンツが置かれているオリジンサーバー、世界各地に配置されるキャッシュサーバーであるエッジサーバーがある。エッジサーバーがキャッシュにコンテンツを持っていれば即配信、なければオリジンサーバーから取得して配信。" },
      { ja: "アロー関数", fr: "fonction fléchée", en: "arrow function",desc: "JavaScriptで関数を短く書くための記法。無名関数である。1行で値を返すだけのときは、return と {} を省略でき、引数が1つのときは()も省略できる。外側（親）のthisを引き継ぐ。" },
      { ja: "無名関数", fr: "fonction anonyme", en: "anonymous function",desc: "名前を付けずに定義される関数のこと。その場限りで使いたい関数や、アロー関数に使う。" },
      { ja: "", fr: "", en: "",desc: "" },
      { ja: "", fr: "", en: "",desc: "" }
          
    ];